version: 2
updates:
  - package-ecosystem: 'npm'
    directory: 'dashgit-web/test/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 20

  # app dependencies are grouped and should be manually updated in the index.html importmap
  - package-ecosystem: 'npm'
    directory: 'dashgit-web/app/'
    groups:
      web-manual-updates:
        patterns:
          - "*"
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 20

  - package-ecosystem: maven
    directory: "dashgit-updater/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 20
